//
// Created by aichao on 2025/2/24.
//

#include <chrono>  // NOLINT
#include <iostream>
#include <string>

#include "csrc/audio/sherpa-onnx/csrc/cxx-api.h"
static int32_t ProgressCallback(const float *samples, int32_t num_samples,
                                float progress, void *arg) {
    fprintf(stderr, "Progress: %.3f%%\n", progress * 100);
    // return 1 to continue generating
    // return 0 to stop generating
    return 1;
}
int32_t main() {
    using namespace sherpa_onnx::cxx;  // NOLINT
    OfflineTtsConfig config;

    config.model.kokoro.model = "./kokoro-int8-multi-lang-v1_1/model.int8.onnx";
    config.model.kokoro.voices = "./kokoro-int8-multi-lang-v1_1/voices.bin";
    config.model.kokoro.tokens = "./kokoro-int8-multi-lang-v1_1/tokens.txt";
    config.model.kokoro.data_dir = "./kokoro-int8-multi-lang-v1_1/espeak-ng-data";
    config.model.kokoro.dict_dir = "./kokoro-int8-multi-lang-v1_1/dict";
    config.model.kokoro.lexicon =
        "./kokoro-int8-multi-lang-v1_1/lexicon-us-en.txt,./kokoro-int8-multi-lang-v1_1/"
        "lexicon-zh.txt";
    config.model.num_threads = 2;
    // If you don't want to see debug messages, please set it to 0
    config.model.debug = false;
    std::string filename = "./generated-kokoro-zh-en-cxx.wav";
    std::string text =
        "中英文语音合成测试。This is generated by next generation Kaldi using "
        "Kokoro without Misaki. 你觉得中英文说的如何呢？";
    auto tts = OfflineTts::Create(config);
    int32_t sid = 52;
    float speed = 1.2;  // larger -> faster in speech speed
#if 0
    // If you don't want to use a callback, then please enable this branch
    GeneratedAudio audio = tts.Generate(text, sid, speed);
#else
    GeneratedAudio audio = tts.Generate(text, sid, speed, ProgressCallback);
#endif
    WriteWave(filename, {audio.samples, audio.sample_rate});
    fprintf(stderr, "Input text is: %s\n", text.c_str());
    fprintf(stderr, "Speaker ID is is: %d\n", sid);
    fprintf(stderr, "Saved to: %s\n", filename.c_str());
    return 0;
}
