//
// Created by aichao on 2025/2/26.
//

#include <chrono>  // NOLINT
#include <iostream>
#include "capi/audio/tts/kokoro_capi.h"

int32_t main() {
    MDStatusCode ret;
    MDModel model;
    MDKokoroParameters parameters = {
        "../../test_data/test_models/kokoro-multi-lang-v1_1/model.onnx",
        "../../test_data/test_models/kokoro-multi-lang-v1_1/voices.bin",
        "../../test_data/test_models/kokoro-multi-lang-v1_1/tokens.txt",
        "../../test_data/test_models/kokoro-multi-lang-v1_1/espeak-ng-data",
        "../../test_data/test_models/kokoro-multi-lang-v1_1/dict",
        "../../test_data/test_models/kokoro-multi-lang-v1_1/lexicon-us-en.txt,"
        "../../test_data/test_models/kokoro-multi-lang-v1_1/lexicon-zh.txt",
        1,
        0
    };

    if ((ret = md_create_kokoro_model(&model, &parameters)) != 0) {
        std::cout << ret << std::endl;
        return ret;
    }
    const char* text = "中英文语音合成测试。This is generated by next generation Kaldi using "
        "Kokoro without Misaki. 你觉得中英文说的如何呢？";
    // 音色
    constexpr int sid = 48;
    // 速度
    constexpr int speed = 1;
    const char* wav_path = "result.wav";
    if ((ret = md_kokoro_model_predict(&model, text, sid, speed, wav_path)) != 0) {
        std::cout << ret << std::endl;
        return ret;
    }
    md_free_kokoro_model(&model);
    return ret;
}
