#
message(STATUS "CMAKE_SYSTEM_NAME: ${CMAKE_SYSTEM_NAME}")
message(STATUS "CMAKE_SYSTEM_PROCESSOR: ${CMAKE_SYSTEM_PROCESSOR}")
message(STATUS "CMAKE_VS_PLATFORM_NAME: ${CMAKE_VS_PLATFORM_NAME}")

# 优先使用系统已安装的 OpenCV（apt / sophon 等），避免必须联网 FetchContent 下载。
# 找不到时再走预编译包下载。
find_package(OpenCV CONFIG QUIET)
if (OpenCV_FOUND)
    message(STATUS "Using system OpenCV: ${OpenCV_VERSION}")
else ()
    set(opencv_5_x_win_x64_static_mt_FILE_NAME "opencv_5_x_win_x64_static_mt.zip")
    set(opencv_5_x_win_x64_static_md_FILE_NAME "opencv_5_x_win_x64_static_md.zip")
    set(opencv_5_x_linux_x64_static_FILE_NAME "opencv_5_x_linux_x64_static.zip")
    set(opencv_5_x_linux_aarch64_static_FILE_NAME "opencv_5_x_linux_aarch64_static.zip")
    set(OPENCV_BASE_URL "https://www.modelscope.cn/models/ChaoII0987/ModelDeploy_cmake_deps/resolve/master")
    include(FetchContent)

    if (${CMAKE_SYSTEM_NAME} STREQUAL "Windows")
        if (WITH_STATIC_CRT)
            set(OPENCV_FILE_NAME ${opencv_5_x_win_x64_static_mt_FILE_NAME})
            set(OPENCV_URL ${OPENCV_BASE_URL}/${OPENCV_FILE_NAME})
            set(OPENCV_HASH "SHA256=86e5bdbce3d2955ef92f295feef1f40171dfdfeac37eaf1b5b141ed8aae3d112")
        else ()
            set(OPENCV_FILE_NAME ${opencv_5_x_win_x64_static_md_FILE_NAME})
            set(OPENCV_URL ${OPENCV_BASE_URL}/${OPENCV_FILE_NAME})
            set(OPENCV_HASH "SHA256=587dc46cdb8154cd29e342ff9ad83e5fcaee247aa312f918c5bf1b1372540c38")
        endif ()
    elseif (${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
        if (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86_64")
            set(OPENCV_FILE_NAME ${opencv_5_x_linux_x64_static_FILE_NAME})
            set(OPENCV_URL ${OPENCV_BASE_URL}/${OPENCV_FILE_NAME})
            set(OPENCV_HASH "SHA256=4a1ec2ec05b8e8a4d4503e2410543a48dc48beea4a4d3c4832375f6ab7edefb2")
        elseif (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "aarch64")
            set(OPENCV_FILE_NAME ${opencv_5_x_linux_aarch64_static_FILE_NAME})
            set(OPENCV_URL ${OPENCV_BASE_URL}/${OPENCV_FILE_NAME})
            set(OPENCV_HASH "SHA256=f6a3668a338270fba5142fae2f661779203cc25a1640cfc8abe6e771cd76f986")
        endif ()
    elseif (${CMAKE_SYSTEM_NAME} STREQUAL "Darwin")
        message(FATAL_ERROR "Unsupported system :" ${CMAKE_SYSTEM_NAME})
    endif ()

    FetchContent_Declare(opencv
            URL
            ${OPENCV_URL}
            URL_HASH ${OPENCV_HASH}
            DOWNLOAD_EXTRACT_TIMESTAMP TRUE
    )

    FetchContent_GetProperties(opencv)
    if (NOT opencv_POPULATED)
        message(STATUS "Downloading opencv from ${OPENCV_URL}")
        FetchContent_Populate(opencv)
    else ()
        message(STATUS "opencv is already populated")
    endif ()
    message(STATUS "opencv is downloaded to ${opencv_SOURCE_DIR}")
    if (NOT opencv_SOURCE_DIR)
        message(FATAL_ERROR "opencv_SOURCE_DIR is not set after population")
    endif ()

    if (${CMAKE_SYSTEM_NAME} STREQUAL "Windows")
        set(OpenCV_DIR "${opencv_SOURCE_DIR}/x64/vc17/staticlib")
    elseif (${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
        if (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86_64")
            set(OpenCV_DIR "${opencv_SOURCE_DIR}/lib/cmake/opencv5")
        elseif (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "aarch64")
            set(OpenCV_DIR "${opencv_SOURCE_DIR}/lib64/cmake/opencv5")
        endif ()
    elseif (${CMAKE_SYSTEM_NAME} STREQUAL "Darwin")
        message(FATAL_ERROR "Unsupported system :" ${CMAKE_SYSTEM_NAME})
    endif ()

    if (NOT DEFINED OpenCV_DIR)
        find_package(OpenCV CONFIG REQUIRED)
    else ()
        find_package(OpenCV CONFIG REQUIRED)
    endif ()
endif ()

if (NOT OpenCV_FOUND)
    message(FATAL_ERROR "build BUILD_VISION depends on opencv,please specifier OpenCV_DIR")
endif ()
message(STATUS "OpenCV version: ${OpenCV_VERSION}")

# OpenCV 5 静态库包含 oneTBB 并行后端（parallel_tbb.cpp.o），链接期需要 libtbb 提供其符号。
# 动态 OpenCV 由系统运行时提供 TBB，无需显式链接。仅静态 OpenCV 5 需要补链。
if (OpenCV_VERSION VERSION_GREATER_EQUAL "5.0")
    if (OpenCV_STATIC OR (DEFINED OpenCV_SHARED AND NOT OpenCV_SHARED))
        find_package(TBB QUIET)
        if (TBB_FOUND)
            list(APPEND DEPENDS TBB::tbb)
            message(STATUS "OpenCV 5 static: linking oneTBB (${TBB_VERSION})")
        else ()
            message(WARNING "OpenCV 5 static requires oneTBB symbols; TBB not found, link may fail")
        endif ()
    endif ()
endif ()
